export const TEST_DISPATCH = "TEST_DISPATCH";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_OPERATOR = "GET_OPERATOR";
export const SET_OPERATOR = "SET_OPERATOR";
export const GET_OPERATORS = "GET_OPERTATORS";
export const DELETE_OPERATOR = "DELETE_OPERTATOR";
export const UPDATE_OPERATOR = "UPDATE_OPERTATOR";
